### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by CichyCze** [discord-modifications/show-hidden-channels#2]
Hi, I don't know if anyone else have the same issue, but this plugin stopped working like a half a month ago for me.
This is the only thing I could find about it:
![image](https://user-images.githubusercontent.com/35575041/151548559-b43fcd4e-9c49-4b48-bcc6-f9ee794fae1f.png)

If some more informations are needed, let me know.

**Comment by marioparaschiv** [comment]
Fixed?

**Comment by CichyCze** [comment]
Oh, it's finally working! Thank you so much.
